cache:
   host: _env:REGISTRYCACHE_PORT_6379_TCP_ADDR
   port: _env:REGISTRYCACHE_PORT_6379_TCP_PORT
   db: 0
cache_lru:
   host: _env:REGISTRYCACHE_PORT_6379_TCP_ADDR
   port: _env:REGISTRYCACHE_PORT_6379_TCP_PORT
   db: 1