FROM ubuntu:14.04
MAINTAINER linux_china linux_china@hotmail.com

# Add Basho's APT repository
RUN apt-get update && apt-get install -y curl zip unzip
RUN curl -L -s get.jenv.io | bash

# RUN /bin/bash -l -c "jenv install ant"
